### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by pedro-mendonca**

### CODE REVIEW

**Comment by devinsays** [comment]
Thanks! Good catch.

**Comment by pedro-mendonca** [comment]
I've checked my old .po and changed the old fuzzy strings to new ones.
I have pt_PT complete in .po according the my last commit and I've filled in every string in Transifex. You now need to update Transifex with this last typo correction.
If you prefer I can pull my .po and .mo.

**Comment by devinsays** [comment]
Just pushed the update to transifex.

**Comment by pedro-mendonca** [comment]
Done, just completed 100% pt_PT on Transifex also. :+1:

**Pull request merged**
